export const APP_CONSTANTS = {
  APP_NAME: "AI Knowledge Platform",
  LINKS: {
    PLACEHOLDER: "#",
  },
  STORAGE_KEYS: {
    USER: "user",
    ACCESS_TOKEN: "access_token",
    THEME: "theme",
  },
  DOCUMENTS: {
    MAX_UPLOAD_FILE_SIZE_BYTES: 5000000,
    POLLING_INTERVAL_MS: 1000,
    POLLING_STATUSES: ["QUEUED", "PROCESSING"],
  },
  MESSAGES: {
    LOADING: "Loading...",
    RELOAD_PAGE: "Reload the page...",
    LOGIN_LOADING: "Logging in...",
    LOGIN_BUTTON_LOADING: "Logging in...",
    LOGIN_SUCCESS: "Login successful",
    LOGOUT_LOADING: "Logging out...",
    LOGOUT_SUCCESS: "Logout Successful",
    LOGOUT_ERROR: "Unable to logout. Please try again.",
    SIGNUP_LOADING: "Creating account...",
    SIGNUP_BUTTON_LOADING: "Creating Account",
    SIGNUP_SUCCESS: "User created successfully. Please login",
    LOGIN_ERROR: "Unable to login. Please try again.",
    SIGNUP_ERROR: "Unable to signup. Please try again.",
    PASSWORD_MISMATCH: "Confirm password doesn't match",
    DOCUMENT_TITLE_REQUIRED: "Document title is required",
    DOCUMENT_FILE_REQUIRED: "Please select a PDF file",
    DOCUMENT_FILE_TYPE_ERROR: "Only PDF files are supported",
    DOCUMENT_FILE_SIZE_ERROR: "PDF file must be 5 MB or smaller",
    DOCUMENT_UPLOAD_DIALOG_TITLE: "Upload document",
    DOCUMENT_UPLOAD_DIALOG_DESCRIPTION:
      "Select a PDF and add a title for your document library.",
    DOCUMENT_UPLOAD_TITLE_LABEL: "Title",
    DOCUMENT_UPLOAD_FILE_LABEL: "PDF file",
    DOCUMENT_UPLOAD_CHOOSE_FILE_BUTTON: "Choose PDF",
    DOCUMENT_UPLOAD_FILE_HELP: "Select one PDF file to upload.",
    DOCUMENT_UPLOAD_REMOVE_FILE_LABEL: "Remove selected file",
    DOCUMENT_UPLOAD_BUTTON: "Upload",
    DOCUMENT_UPLOAD_CANCEL_BUTTON: "Cancel",
    DOCUMENT_UPLOAD_LOADING: "Uploading document...",
    DOCUMENT_UPLOAD_BUTTON_LOADING: "Uploading...",
    DOCUMENT_UPLOAD_SUCCESS: "Document uploaded",
    DOCUMENT_UPLOAD_ERROR: "Unable to upload document",
    DOCUMENT_RENAME_PROMPT: "Rename document",
    DOCUMENT_RENAME_DIALOG_DESCRIPTION:
      "Update the title shown in your document library.",
    DOCUMENT_RENAME_TITLE_LABEL: "Title",
    DOCUMENT_RENAME_CANCEL_BUTTON: "Cancel",
    DOCUMENT_RENAME_SAVE_BUTTON: "Save changes",
    DOCUMENT_RENAME_LOADING: "Renaming document...",
    DOCUMENT_RENAME_SUCCESS: "Document renamed",
    DOCUMENT_RENAME_ERROR: "Unable to rename document",
    DOCUMENT_DELETE_DIALOG_TITLE: "Delete document",
    DOCUMENT_DELETE_CONFIRM: (title: string) =>
      `Delete "${title}"? This cannot be undone.`,
    DOCUMENT_DELETE_CANCEL_BUTTON: "Cancel",
    DOCUMENT_DELETE_BUTTON: "Delete",
    DOCUMENT_DELETE_LOADING: "Deleting document...",
    DOCUMENT_DELETE_SUCCESS: "Document deleted",
    DOCUMENT_DELETE_ERROR: "Unable to delete document",
    DOCUMENT_RETRY_LOADING: "Retrying document...",
    DOCUMENT_RETRY_SUCCESS: "Document retry started",
    DOCUMENT_RETRY_ERROR: "Unable to retry document",
    DOCUMENT_LOAD_ERROR: "Unable to load documents",
    CHAT_DOCUMENT_DIALOG_TITLE: "Choose document",
    CHAT_DOCUMENT_DIALOG_DESCRIPTION:
      "Select an uploaded document or upload a new PDF before starting chat.",
    CHAT_DOCUMENT_NOT_READY:
      "Document uploaded, but it is not ready for chat yet. Refresh and select it when ready.",
    CHAT_SEND_LOADING: "Thinking...",
    CHAT_SEND_ERROR: "Unable to send message",
    CHAT_QUERY_REQUIRED: "Enter a question before sending",
    LOAD_RELOAD_PAGE: "Loading... Reload if it takes time...",
  },
} as const
